{% set version = "1.0.0" %}

package:
  name: symuvia
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  preserve_egg_dir: True

requirements:
  build:
    - {{ compiler('cxx') }}  #[linux]
    - make
    - cmake
    - python=3.9
  host:
    - boost
    - boost-cpp
    - libgdal=3.2.1
    - xerces-c=3.2.3
    - xqilla=2.3.4
    - rapidjson
    - unixodbc
    - python=3.9
  run:
    - boost
    - boost-cpp
    - libgdal=3.2.1
    - xerces-c=3.2.3
    - xqilla=2.3.4
    - rapidjson
    - unixodbc
    - python=3.9


test:
  source_files:
    - test/SingleLink_symuvia.xml
    - test/SingleLink_symumaster.xml
  commands:
    - SymuMasterLauncher test/SingleLink_symumaster.xml
