{% set version = "1.0.0" %}

package:
  name: symuvia
  version: {{ version }}

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - make
    - cmake
  host:
    - boost
    - boost-cpp
    - libgdal
    - xerces-c
    - xqilla
    - rapidjson
    - unixodbc
    - python

  run:
    - boost
    - boost-cpp
    - libgdal
    - xerces-c
    - xqilla
    - rapidjson
    - unixodbc
    - python
