name: Build SymuCore SymuVia

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  ###################
  # BUILDING ON OSX
  ###################
  build-osx:
    runs-on: macos-latest
    steps:
    - name: Checkout SymuVia
      uses: actions/checkout@v2
      with:
        path: symuvia
        
    - name: Preparing Build System
      run: |
        brew update
        brew install cmake boost boost-python3 gdal xqilla rapidjson python

    - name: Building SymuVia
      run: |
        mkdir -p symuvia/cmake-build 
        cd symuvia/cmake-build 
        cmake .. 
        make -j2
